<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5bc90ebd7f489',
	'title' => 'Campos usuário',
	'fields' => array(
		array(
			'key' => 'field_5bc90ec2d0231',
			'label' => 'Campo 1',
			'name' => 'campo_1_asfawwgweq',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bc90eced0232',
			'label' => 'Campo 2',
			'name' => 'campo_2_koighoigogs',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'rascunho-autom-tico',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5bd1ddbb0502a',
	'title' => 'Configurações APP',
	'fields' => array(
		array(
			'key' => 'field_5bd1ddc4ee80c',
			'label' => 'APP Key',
			'name' => 'mautfunnel_appintegration_app_key',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bd1de1cee80d',
			'label' => 'APP Client Key',
			'name' => 'mautfunnel_appintegration_app_client_key',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'appintegration-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5bbd6b02bcf2b',
	'title' => 'Configurações da Mensagem',
	'fields' => array(
		array(
			'key' => 'field_5bbd6b193c756',
			'label' => 'Selecionar Funil',
			'name' => 'aptwhatsmsg_funnel_id',
			'type' => 'post_object',
			'instructions' => 'Informe a qual funil essa mensagem será vinculada.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'aptemailserver',
			),
			'taxonomy' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5bbd6e843c757',
			'label' => 'Tipo de Mensagem',
			'name' => 'aptwhatsmsg_type',
			'type' => 'select',
			'instructions' => '<strong>Mensagem Padrão:</strong> Mensagem que podem ser enviadas pelo usuário a qualquer momento. Podem ser vinculadas a estágios específicos ou ficarem disponíveis em todos os estágios.<br /><br /><strong>Mensagem Pendente:</strong>Mensagens que fazem parte de campanhas de automação.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'padrao' => 'Mensagem Padrão',
				'pendente' => 'Mensagem Pendente',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bbd714e3c75c',
			'label' => 'Configurações',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bbd6e843c757',
						'operator' => '==',
						'value' => 'pendente',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bbd725a3c760',
			'label' => 'Comportamento',
			'name' => 'aptwhatsmsg_behavior',
			'type' => 'select',
			'instructions' => '<strong>Apagar Anterior:</strong> Quando uma nova mensagem for gerada, a mensagem anterior será removida da lista de pendentes e será listada como "não enviada". Na lista de pendentes será exibida apenas a última mensagem.<br /><br /><strong>(DESATIVADO) Envio Relativo à Mensagem Anterior:</strong> Nesse caso, nunca haverá mensagem acumulada pois a próxima mensagem será gerada apenas quando a anterior for enviada.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'remove_previous' => 'Apagar Anterior',
				'send_relative' => 'Envio Relativo à Mensagem Anterior',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bbd72313c75f',
			'label' => 'Configurações',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bbd6e843c757',
						'operator' => '==',
						'value' => 'padrao',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bbd6fc73c759',
			'label' => 'Quando Usar Mensagem',
			'name' => 'aptwhatsmsg_use_if',
			'type' => 'text',
			'instructions' => 'Escreva uma instrução curta de quando o usuário deve usar essa mensagem. Recomendamos que use entre 3 e 5 palavras se possível.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Enviar quando contato...',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bbd71813c75d',
			'label' => 'Associar a Estágios Específicos',
			'name' => 'aptwhatsmsg_specific_stages',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Exibir apenas em alguns estágios específicos',
			'ui_off_text' => 'Exibir em todos os estágios',
		),
		array(
			'key' => 'field_5bbd71e33c75e',
			'label' => 'Selecionar Estágios',
			'name' => 'aptwhatsmsg_stages',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bbd71813c75d',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'aptfunnelstage',
			),
			'taxonomy' => array(
			),
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5bf33a2bc920c',
			'label' => 'Selecionar Funis',
			'name' => 'aptwhatsmsg_funnels',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bbd71813c75d',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'aptemailserver',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5bbd6fa13c758',
			'label' => 'Conteúdo',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bbd6e843c757',
						'operator' => '!=',
						'value' => '',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bbd70763c75a',
			'label' => 'Conteúdo da Mensagem',
			'name' => 'aptwhatsmsg_body',
			'type' => 'textarea',
			'instructions' => 'Escreva o texto da mensagem. Para quebra de linha utilize <strong><br></strong>, Você também pode utilizar como variáveis campos do sistema de emails a que a mensagem está conectada. Use <strong>%%nome_do_campo%%</strong> e o sistema irá preencher com o valor do campo de nome <strong>nome_do_campo</strong>.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'aptwhatsmsg',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5b89f280a9525',
	'title' => 'Configurações do Estágio',
	'fields' => array(
		array(
			'key' => 'field_5b89f29f4bd95',
			'label' => 'Email Server',
			'name' => 'mauticfunnelint_email_system_rel',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'aptemailserver',
			),
			'taxonomy' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5b89f3abfd34c',
			'label' => 'ID no Sistema de Emails',
			'name' => 'mauticfunnelint_stage_id',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b89f411f0df3',
			'label' => 'Estágios Disponíveis',
			'name' => 'mauticfunnelint_available_stage',
			'type' => 'post_object',
			'instructions' => 'Estágios que serão exibidos no APP para que o usuário possa fazer a migração manual.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'aptfunnelstage',
			),
			'taxonomy' => array(
			),
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5bbd75fffdc25',
			'label' => 'Estágios Permitidos Automático',
			'name' => 'mauticfunnelint_available_stage_automation',
			'type' => 'post_object',
			'instructions' => 'Quando o lead chegar em qualquer página do sistema, o sistema verifica se o "novo estágio" está na lista dos estágios permitidos do lead (baseado no estágio atual). Só após essa verificação a mudança de estágio é realizada.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'aptfunnelstage',
			),
			'taxonomy' => array(
			),
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'aptfunnelstage',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5b85dcd2374c6',
	'title' => 'Configurações Email Servers',
	'fields' => array(
		array(
			'key' => 'field_5b85dd3f4c3bc',
			'label' => 'Sistema de Emails',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b8818cd90b94',
			'label' => 'Sistema de Emails',
			'name' => 'mauticfunnelint_email_system',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'mautic' => 'Mautic',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b88190890b95',
			'label' => 'API',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b8818cd90b94',
						'operator' => '==',
						'value' => 'mautic',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b85dd584c3bd',
			'label' => 'URL de Instalação Mautic',
			'name' => 'mauticfunnelint_intallation_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b87ecc8bdf42',
			'label' => 'Username',
			'name' => 'mauticfunnelint_username',
			'type' => 'text',
			'instructions' => 'Para que a API com o banco de dados funcione é preciso estar liberada a integração BÁSICA e você precisa usar os dados de um ADMINISTRADOR com acesso completo ao sistema.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b87ecdcbdf43',
			'label' => 'Senha',
			'name' => 'mauticfunnelint_password',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b85e0a08b063',
			'label' => 'Novo Usuário',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b8818cd90b94',
						'operator' => '==',
						'value' => 'mautic',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b85e0be8b064',
			'label' => 'Criar Novo Usuário',
			'name' => 'mauticfunnelint_create_new_user',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5b85e10f8b065',
			'label' => 'ID da Função no Mautic',
			'name' => 'mauticfunnelint_mautic_role_id',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b85e0be8b064',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b85e1368b066',
			'label' => 'Senha Padrão',
			'name' => 'mauticfunnelint_user_password',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b85e0be8b064',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b85e2128b067',
			'label' => 'ID do Admin no Mautic',
			'name' => 'mauticfunnelint_admin_id',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b85e0be8b064',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b9d9f005b943',
			'label' => 'Campo WP',
			'name' => 'mauticfunnelint_wp_field_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b85e0be8b064',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b9d715583a44',
			'label' => 'Banco de Dados',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b8818cd90b94',
						'operator' => '==',
						'value' => 'mautic',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b9d99734f866',
			'label' => 'Host',
			'name' => 'mauticfunnelint_mautic_db_host',
			'type' => 'text',
			'instructions' => 'Para que a API com o banco de dados funcione é preciso estar liberada a integração BÁSICA e você precisa usar os dados de um ADMINISTRADOR com acesso completo ao sistema.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b9d99cd4f869',
			'label' => 'Name',
			'name' => 'mauticfunnelint_mautic_db_name',
			'type' => 'text',
			'instructions' => 'Para que a API com o banco de dados funcione é preciso estar liberada a integração BÁSICA e você precisa usar os dados de um ADMINISTRADOR com acesso completo ao sistema.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b9d999b4f867',
			'label' => 'User',
			'name' => 'mauticfunnelint_mautic_db_user',
			'type' => 'text',
			'instructions' => 'Para que a API com o banco de dados funcione é preciso estar liberada a integração BÁSICA e você precisa usar os dados de um ADMINISTRADOR com acesso completo ao sistema.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b9d99bd4f868',
			'label' => 'Key',
			'name' => 'mauticfunnelint_mautic_db_key',
			'type' => 'text',
			'instructions' => 'Para que a API com o banco de dados funcione é preciso estar liberada a integração BÁSICA e você precisa usar os dados de um ADMINISTRADOR com acesso completo ao sistema.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bb36cb41f91e',
			'label' => 'Prefix',
			'name' => 'mauticfunnelint_mautic_db_prefix',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bbe58fb017e9',
			'label' => 'Campos',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b8818cd90b94',
						'operator' => '==',
						'value' => 'mautic',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bbd74d2c78b1',
			'label' => 'Campo Mautic Última Mensagem Enviada',
			'name' => 'mauticfunnelint_maut_field_last_msg',
			'type' => 'text',
			'instructions' => 'É preciso criar no sistema de emails um campo contendo DATA e HORA. Esse campo armazenará o horário de envio da última mensagem WhatsApp.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bbff1bf83765',
			'label' => 'Campo Mautic WhatsApp',
			'name' => 'mauticfunnelint_maut_field_whatsapp',
			'type' => 'text',
			'instructions' => 'Você pode manter o campo padrão "mobile" ou pode criar um campo específico para WhatsApp. Se criar um novo, insira aqui o nome do campo.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'mobile',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bbff73b818d8',
			'label' => 'WhatsApp Number Prefix',
			'name' => 'mauticfunnelint_maut_whatsapp_prefix',
			'type' => 'number',
			'instructions' => 'Você pode manter o campo padrão "mobile" ou pode criar um campo específico para WhatsApp. Se criar um novo, insira aqui o nome do campo.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 55,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b9f49f5840df',
			'label' => 'Campo Mautic Patrocinador Email',
			'name' => 'mauticfunnelint_maut_field_sponsor_email',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b9f4a14840e0',
			'label' => 'Campo Mautic Patrocinador Nome',
			'name' => 'mauticfunnelint_maut_field_sponsor_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b9f4a67840e1',
			'label' => 'Campo Mautic Patrocinador Username',
			'name' => 'mauticfunnelint_maut_field_sponsor_username',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b9f4a7d840e2',
			'label' => 'Campo Mautic Patrocinador ID',
			'name' => 'mauticfunnelint_maut_field_sponsor_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b9f067489a95',
			'label' => 'Formulários',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b8818cd90b94',
						'operator' => '==',
						'value' => 'mautic',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b9f068789a96',
			'label' => 'Código de Formulário',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<form method="post" action="SEUDOMINIO?aptFunnelAction=lead_form">

<input name="firstname" value="" type="text" />
<input name="lastname" value="" type="text" />
<input name="email" value="" type="text" />
<input name="mobile" value="" type="text" />	
	
<input type="hidden" name="sponsor" value="%%user_login%%"/>
<input type="hidden" name="server" value="EMAIL_SERVER_ID"/>
<input type="hidden" name="redirect_to" value="REDIRECT_URL"/>
<input type=\'hidden\' name="aptlinkcomp" value="{aptlinkcomp}"/>
<input type=\'hidden\' name="aptlinkshared" value="{aptlinkshared}"/>
	
<button type="submit" name="submit">Enviar</button>

</form>',
			'new_lines' => 'wpautop',
			'esc_html' => 1,
		),
		array(
			'key' => 'field_5b9f06e989a97',
			'label' => 'Instruções',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '* Lembre-se de substituir EMAIL_SERVER_ID pelo ID do Email Server usado para construir o funil.

* Lembre-se de utilizar o shortcode [pag_person] em torno do formulário para personalizar qualquer campo necessário.

* Substitua SEUDOMINIO pelo domínio de seu website.

* Substitua REDIRECT_TO pelo endereço para onde pretende redirecionar o lead após o cadastro.',
			'new_lines' => 'wpautop',
			'esc_html' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'aptemailserver',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5b85f174ce776',
	'title' => 'Opções de Funil - Ações',
	'fields' => array(
		array(
			'key' => 'field_5b8b1b7be808b',
			'label' => 'Email Server',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b89c1d23830c',
			'label' => 'Email Server',
			'name' => 'mauticfunnelint_email_server_reference',
			'type' => 'post_object',
			'instructions' => 'Selecione em qual Servidor de Email o lead será procurado ao navegar por esta página',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'aptemailserver',
			),
			'taxonomy' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5b8b1b90e808c',
			'label' => 'Bloquear',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b89c4223830e',
			'label' => 'Mensagem ou Redirecionar?',
			'name' => 'mauticfunnelint_block_mode',
			'type' => 'select',
			'instructions' => 'Caso você queira que essa página seja acessível apenas a Leads que estão no funil, marque escolha como o sistema deve tratar os visitantes que não são leads.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'none' => 'Não bloquear visitantes',
				'redirect' => 'Redirecionar para página',
				'message' => 'Exibir mensagem',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b89cbf498c98',
			'label' => 'Redirecionar para...',
			'name' => 'mauticfunnelint_redirect_to',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b89c4223830e',
						'operator' => '==',
						'value' => 'redirect',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'taxonomy' => array(
			),
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
		),
		array(
			'key' => 'field_5b89cc4698c99',
			'label' => 'Mensagem a exibir',
			'name' => 'mauticfunnelint_message_block',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b89c4223830e',
						'operator' => '==',
						'value' => 'message',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5b8b1bbfe808d',
			'label' => 'Funil',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b89cc8f8a3bd',
			'label' => 'Tags para adicionar',
			'name' => 'mauticfunnelint_add_tags',
			'type' => 'text',
			'instructions' => 'Insira as tags separadas por vírgulas',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b89fcff216fd',
			'label' => 'Mudar para estágio',
			'name' => 'mauticfunnelint_new_stage',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'aptfunnelstage',
			),
			'taxonomy' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

?>